# fly.toml app configuration file generated for fragrant-dew-6080 on 2023-08-16T20:46:19-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'egghead-blog'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
